let BasicUrl = 'http://devapi.tatadisasterresponse.com/'
export default BASEURLS = {
    LoginUrl: BasicUrl + 'Api/app-user-login',
    UpdateUser: BasicUrl + 'api/app-update-user-profile',
    GenrateCode: BasicUrl + 'api/view-generate-code?userid=',
    ResponceCode: BasicUrl + 'api/view-generate-team?responce_code=',
    DeleteResponseBeneficiary: BasicUrl + 'api/delete-response-beneficiary-list',
    UpdateResposeList: BasicUrl + 'api/update-response-beneficiary-list',
    AddResponseList: BasicUrl + 'api/add-response-beneficiary-list',
    GetHemletReport: BasicUrl + 'api/get-hemlet-report?village_sys_id=',
    GetVillageReport: BasicUrl + 'api/get-village-report?village_sys_id=',
    GetGramPanchayatReport: BasicUrl + 'api/get-gram-panchayat-report?block_sys_id=',
    GetBlockReport: BasicUrl + 'api/get-block-report?district_sys_id=',
    PostVillageName: BasicUrl + 'api/post-village-name',
    PostPanchayatName: BasicUrl + 'api/post-gram-panchayat-name',
    PostBlockName: BasicUrl + 'api/post-block-name',
    PostDistrictName: BasicUrl + 'api/post-district-name',
    PostHemletName: BasicUrl + 'api/post-hemlet-name',
    AddNotice: BasicUrl + 'api/add-notice-board',
    AddMappingData: BasicUrl + 'api/add-response-location-mapping',
    UpadateMapping: BasicUrl + 'api/update-response-location-mapping',
    AddBeneficialData: BasicUrl + 'api/add-response-beneficiary-list',
    UpdateBeneficiaryData: BasicUrl + 'api/update-response-beneficiary-list',
    UpdateNotice: BasicUrl + 'api/update-notice-board',
    AddNoticeComment: BasicUrl + 'api/add-notice-comment',
    Distric:BasicUrl + 'api/get-district?state_id=',
    GetBlockReport: BasicUrl + 'api/get-block-report?district_sys_id=',
    PostGallaryAdd:BasicUrl + 'api/post-image-gallery',
    getImageGallary: BasicUrl +'api/get-image-gallery?created_by=',
    getTeamlist:BasicUrl + 'api/view-generate-team?responce_code=',
    getNoticCommentView:BasicUrl + 'api/get-notice-comment-view?notice_comment_sys_id=',
    ViewNoticeView: BasicUrl + 'api/view-notice-board?response_code=',
    DeleteNoticeBoard : BasicUrl +'api/delete-notice-notice-board',
    get_gram_panchayat_report: BasicUrl +'api/get-gram-panchayat-report?block_sys_id=',
    getVillageReport : BasicUrl + 'api/get-village-report?village_sys_id=',
    getHemletReport : BasicUrl + 'api/get-hemlet-report?village_sys_id=',
    ViewPartnerName : BasicUrl + 'api/view-partner-name?hemlet_sys_id=',
    ViewBeneficiaryCount : BasicUrl +'api/view-beneficiary-count?response_code=',
    ViewGenerateCode : BasicUrl +'api/view-generate-code?userid=',
    getAppOtpGenerate: BasicUrl +'api/get-app-otp-generate?email=',
    ViewResponselocationMappingDetails: BasicUrl +'api/view-response-location-mapping-details?response_code=',
    ViewResponseBeneficiary: BasicUrl + 'api/view-response-beneficiary?response_code=',
    DeleteMappinglocationlist:BasicUrl + 'api/delete-mapping-location-list?location_mapping_sys_id=',
}
